POST https://fso-phonebook-an72.onrender.com/api/persons
Content-Type: application/json

{
  "name": "Test",
  "number": "0605040302"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Test",
  "number": "040-22334455"
}